CREATE TABLE IF NOT EXISTS teachers (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  teacher_id          INTEGER NOT NULL REFERENCES teachers(id),
  title               TEXT NOT NULL,
  topic               TEXT,
  objectives          TEXT,  -- JSON array of strings
  vocabulary          TEXT,  -- JSON array of {word, definition}
  language_forms      TEXT,  -- JSON array of strings
  persona_name        TEXT DEFAULT 'Alex',
  persona_description TEXT,
  active              INTEGER DEFAULT 1,
  created_at          DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id         INTEGER NOT NULL REFERENCES tasks(id),
  student_name    TEXT NOT NULL,
  level           TEXT,      -- beginner | intermediate | advanced
  interests       TEXT,      -- JSON array
  learning_style  TEXT,      -- visual | auditory | reading | kinesthetic
  conversation_id TEXT,      -- ElevenLabs conversation ID
  transcript      TEXT,      -- JSON array of {role, message, time_in_call_secs}
  outline         TEXT,      -- JSON conversation plan generated by Gemini at session start
  started_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  ended_at        DATETIME
);
